(require 'pth)

(define (looper str)
  (let ((count 0))
    (letrec ((f (lambda ()
                  (inc! count)
                  (display (concat str (number->string count)))
                  (display "\n")
                  (pth:usleep (* 10 1000))
                  (f))))
      f)))

(pth:spawn (looper "hello:   "))
(pth:spawn (looper "goodbye: "))
(pth:spawn (looper "middle:  "))
(pth:spawn (looper "end:     "))
(pth:join (pth:spawn (looper "count: ")))
